import type { NextApiRequest, NextApiResponse } from 'next';
import { successResponse, errors } from '../../../lib/apiResponse';

// 15+ Government Schemes for farmers
const GOVERNMENT_SCHEMES = [
  {
    id: 'pm-kisan',
    schemeCode: 'PM-KISAN',
    name: 'PM Kisan Samman Nidhi',
    nameHindi: 'पीएम किसान सम्मान निधि',
    ministry: 'Ministry of Agriculture',
    category: 'SUBSIDY',
    shortDescription: 'Direct income support of ₹6000/year to farmer families',
    shortDescriptionHindi: 'किसान परिवारों को ₹6000/वर्ष की प्रत्यक्ष आय सहायता',
    benefits: { amount: 6000, frequency: 'yearly', installments: 3 },
    eligibility: { landRequired: true, maxLand: null, incomeLimit: null },
    documents: ['Aadhaar Card', 'Bank Account', 'Land Records', 'Mobile Number'],
    applicationUrl: 'https://pmkisan.gov.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'pmfby',
    schemeCode: 'PMFBY',
    name: 'Pradhan Mantri Fasal Bima Yojana',
    nameHindi: 'प्रधानमंत्री फसल बीमा योजना',
    ministry: 'Ministry of Agriculture',
    category: 'INSURANCE',
    shortDescription: 'Crop insurance at subsidized premium rates',
    shortDescriptionHindi: 'रियायती प्रीमियम दरों पर फसल बीमा',
    benefits: { premiumSubsidy: '50-90%', maxCoverage: 'Full crop value' },
    eligibility: { landRequired: true, loanee: 'Both loanee and non-loanee' },
    documents: ['Aadhaar Card', 'Bank Account', 'Land Records', 'Crop Sowing Certificate'],
    applicationUrl: 'https://pmfby.gov.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'kcc',
    schemeCode: 'KCC',
    name: 'Kisan Credit Card',
    nameHindi: 'किसान क्रेडिट कार्ड',
    ministry: 'Ministry of Finance',
    category: 'LOAN',
    shortDescription: 'Easy credit up to ₹3 lakh at 4% interest',
    shortDescriptionHindi: '4% ब्याज पर ₹3 लाख तक आसान ऋण',
    benefits: { maxLoan: 300000, interestRate: 4, repaymentPeriod: '1 year' },
    eligibility: { landRequired: true, minAge: 18, maxAge: 75 },
    documents: ['Aadhaar Card', 'PAN Card', 'Land Records', 'Passport Photo'],
    applicationUrl: 'https://www.nabard.org/kcc',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'pmksy',
    schemeCode: 'PMKSY',
    name: 'PM Krishi Sinchayee Yojana',
    nameHindi: 'पीएम कृषि सिंचाई योजना',
    ministry: 'Ministry of Agriculture',
    category: 'IRRIGATION',
    shortDescription: '55-90% subsidy on micro irrigation systems',
    shortDescriptionHindi: 'सूक्ष्म सिंचाई प्रणालियों पर 55-90% सब्सिडी',
    benefits: { subsidyPercent: '55-90%', covers: 'Drip and Sprinkler irrigation' },
    eligibility: { landRequired: true, waterSource: 'Required' },
    documents: ['Aadhaar Card', 'Land Records', 'Bank Account', 'Quotation from supplier'],
    applicationUrl: 'https://pmksy.gov.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'pkvy',
    schemeCode: 'PKVY',
    name: 'Paramparagat Krishi Vikas Yojana',
    nameHindi: 'परंपरागत कृषि विकास योजना',
    ministry: 'Ministry of Agriculture',
    category: 'SUBSIDY',
    shortDescription: '₹50,000/hectare for organic farming over 3 years',
    shortDescriptionHindi: 'जैविक खेती के लिए 3 वर्षों में ₹50,000/हेक्टेयर',
    benefits: { amount: 50000, perUnit: 'hectare', duration: '3 years' },
    eligibility: { landRequired: true, groupFormation: '20+ farmers needed' },
    documents: ['Aadhaar Card', 'Land Records', 'Group Registration'],
    applicationUrl: 'https://pgsindia-ncof.gov.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'soil-health',
    schemeCode: 'SHC',
    name: 'Soil Health Card Scheme',
    nameHindi: 'मृदा स्वास्थ्य कार्ड योजना',
    ministry: 'Ministry of Agriculture',
    category: 'TRAINING',
    shortDescription: 'Free soil testing and nutrient recommendations',
    shortDescriptionHindi: 'मुफ्त मिट्टी परीक्षण और पोषक तत्व सिफारिशें',
    benefits: { cost: 'Free', frequency: 'Every 2 years' },
    eligibility: { landRequired: true },
    documents: ['Aadhaar Card', 'Land Location Details'],
    applicationUrl: 'https://soilhealth.dac.gov.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'enam',
    schemeCode: 'eNAM',
    name: 'National Agriculture Market (eNAM)',
    nameHindi: 'राष्ट्रीय कृषि बाज़ार (ई-नाम)',
    ministry: 'Ministry of Agriculture',
    category: 'MARKETING',
    shortDescription: 'Online trading platform for agricultural commodities',
    shortDescriptionHindi: 'कृषि उपज के लिए ऑनलाइन व्यापार मंच',
    benefits: { access: 'Pan-India markets', fees: 'Reduced transaction costs' },
    eligibility: { landRequired: false },
    documents: ['Aadhaar Card', 'Bank Account', 'Mobile Number'],
    applicationUrl: 'https://enam.gov.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'pm-kusum',
    schemeCode: 'PM-KUSUM',
    name: 'PM-KUSUM (Solar Pump)',
    nameHindi: 'पीएम-कुसुम (सोलर पंप)',
    ministry: 'Ministry of New and Renewable Energy',
    category: 'EQUIPMENT',
    shortDescription: '90% subsidy on solar pumps for irrigation',
    shortDescriptionHindi: 'सिंचाई के लिए सोलर पंप पर 90% सब्सिडी',
    benefits: { subsidyPercent: 90, pumpCapacity: 'Up to 7.5 HP' },
    eligibility: { landRequired: true, existingConnection: 'Not required' },
    documents: ['Aadhaar Card', 'Land Records', 'Bank Account', 'Electricity Bill'],
    applicationUrl: 'https://pmkusum.mnre.gov.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'nbm',
    schemeCode: 'NBM',
    name: 'National Beekeeping & Honey Mission',
    nameHindi: 'राष्ट्रीय मधुमक्खी पालन एवं शहद मिशन',
    ministry: 'Ministry of Agriculture',
    category: 'SUBSIDY',
    shortDescription: 'Support for beekeeping with 40-60% subsidy',
    shortDescriptionHindi: 'मधुमक्खी पालन के लिए 40-60% सब्सिडी सहायता',
    benefits: { subsidyPercent: '40-60%', training: 'Free' },
    eligibility: { landRequired: false, training: 'Recommended' },
    documents: ['Aadhaar Card', 'Bank Account'],
    applicationUrl: 'https://nbb.gov.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'rkvy',
    schemeCode: 'RKVY',
    name: 'Rashtriya Krishi Vikas Yojana',
    nameHindi: 'राष्ट्रीय कृषि विकास योजना',
    ministry: 'Ministry of Agriculture',
    category: 'GRANT',
    shortDescription: 'Grants for agricultural infrastructure development',
    shortDescriptionHindi: 'कृषि अवसंरचना विकास के लिए अनुदान',
    benefits: { coverage: 'Various agricultural projects' },
    eligibility: { applicationType: 'Through state government' },
    documents: ['Project Proposal', 'Land Records'],
    applicationUrl: 'https://rkvy.nic.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'up-kisan-uday',
    schemeCode: 'UP-UDAY',
    name: 'UP Kisan Uday Yojana',
    nameHindi: 'यूपी किसान उदय योजना',
    ministry: 'UP Agriculture Department',
    category: 'EQUIPMENT',
    shortDescription: 'Free solar pumps for UP farmers',
    shortDescriptionHindi: 'यूपी किसानों के लिए मुफ्त सोलर पंप',
    benefits: { cost: 'Free', capacity: '5-10 HP solar pumps' },
    eligibility: { state: 'UP', existingConnection: 'Required' },
    documents: ['Aadhaar Card', 'Land Records', 'Electricity Connection Proof'],
    applicationUrl: 'https://upagripardarshi.gov.in',
    state: 'UP',
    status: 'ACTIVE',
  },
  {
    id: 'up-gopalak',
    schemeCode: 'UP-GOPALAK',
    name: 'UP Gopalak Yojana',
    nameHindi: 'यूपी गोपालक योजना',
    ministry: 'UP Animal Husbandry',
    category: 'LOAN',
    shortDescription: 'Interest-free loan for dairy farming in UP',
    shortDescriptionHindi: 'यूपी में डेयरी फार्मिंग के लिए ब्याज मुक्त ऋण',
    benefits: { maxLoan: 900000, interestRate: 0, repayment: '5 years' },
    eligibility: { state: 'UP', minAnimals: 5 },
    documents: ['Aadhaar Card', 'Land/Shed Proof', 'Bank Account'],
    applicationUrl: 'https://upahd.up.gov.in',
    state: 'UP',
    status: 'ACTIVE',
  },
  {
    id: 'krishak-durghatna',
    schemeCode: 'MKDBY',
    name: 'Mukhyamantri Krishak Durghatna Kalyan Yojana',
    nameHindi: 'मुख्यमंत्री कृषक दुर्घटना कल्याण योजना',
    ministry: 'UP Agriculture Department',
    category: 'INSURANCE',
    shortDescription: 'Accident insurance up to ₹5 lakh for UP farmers',
    shortDescriptionHindi: 'यूपी किसानों के लिए ₹5 लाख तक दुर्घटना बीमा',
    benefits: { deathCoverage: 500000, disabilityCoverage: 'Up to ₹5 lakh' },
    eligibility: { state: 'UP', age: '18-70 years' },
    documents: ['Aadhaar Card', 'Land Records', 'Age Proof'],
    applicationUrl: 'https://kisandurghatna.up.gov.in',
    state: 'UP',
    status: 'ACTIVE',
  },
  {
    id: 'pmay-g',
    schemeCode: 'PMAY-G',
    name: 'PM Awas Yojana (Gramin)',
    nameHindi: 'पीएम आवास योजना (ग्रामीण)',
    ministry: 'Ministry of Rural Development',
    category: 'SUBSIDY',
    shortDescription: '₹1.20 lakh assistance for rural housing',
    shortDescriptionHindi: 'ग्रामीण आवास के लिए ₹1.20 लाख सहायता',
    benefits: { amount: 120000, additionalToilet: 12000 },
    eligibility: { rural: true, houseless: true, incomeLimit: 'BPL' },
    documents: ['Aadhaar Card', 'BPL Card', 'Land for House'],
    applicationUrl: 'https://pmayg.nic.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
  {
    id: 'sub-mission-seed',
    schemeCode: 'SMSP',
    name: 'Sub-Mission on Seeds and Planting Material',
    nameHindi: 'बीज एवं रोपण सामग्री पर उप-मिशन',
    ministry: 'Ministry of Agriculture',
    category: 'SEEDS',
    shortDescription: 'Subsidized quality seeds for farmers',
    shortDescriptionHindi: 'किसानों के लिए रियायती गुणवत्ता वाले बीज',
    benefits: { subsidyPercent: '50-75%', covers: 'Certified seeds' },
    eligibility: { landRequired: true },
    documents: ['Aadhaar Card', 'Land Records'],
    applicationUrl: 'https://seednet.gov.in',
    state: 'NATIONAL',
    status: 'ACTIVE',
  },
];

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') {
    return errors.methodNotAllowed(res, ['GET']);
  }

  try {
    const { category, state, status } = req.query;

    let filteredSchemes = GOVERNMENT_SCHEMES;
    
    if (category && typeof category === 'string') {
      filteredSchemes = filteredSchemes.filter(s => s.category === category);
    }
    if (state && typeof state === 'string') {
      filteredSchemes = filteredSchemes.filter(s => 
        s.state === 'NATIONAL' || s.state === state.toUpperCase()
      );
    }
    if (status && typeof status === 'string') {
      filteredSchemes = filteredSchemes.filter(s => s.status === status);
    }

    return successResponse(res, {
      schemes: filteredSchemes,
      total: filteredSchemes.length,
      categories: [...new Set(GOVERNMENT_SCHEMES.map(s => s.category))],
    });

  } catch (error) {
    console.error('Schemes error:', error);
    return errors.serverError(res, error as Error);
  }
}
